# Generated by Django 3.1.4 on 2020-12-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traxxas',
            name='category',
            field=models.CharField(choices=[('monster_trucks', 'MONSTER TRUCKS'), ('on_road_cars', 'ON ROAD CARS'), ('short_course_trucks', 'SHORT COURSE TRUCKS'), ('stadium_trucks', 'STADIUM TRUCKS')], default='monster_trucks', max_length=20),
        ),
    ]
